### ISSUE TITLE
Add Team Members as Collaborators

### ISSUE THREAD

**Issue by atharen** [danielsna/team-2#1]
For a group to work, there needs to be more than 1 individual.
Add all the members in our group as Collaborators.

**Comment by AbelThar** [comment]
Let A stand for: "Group is working"
Let B stand for: "More than 1 individual in the group"
Let C stand for: "Add individuals to the group"

B=>A, ¬B=>C    |-   ¬A=>C

**Comment by mattsc98** [comment]
tkunx faggot
