### ISSUE TITLE
[CRITICAL] Recipe_Book_Draft_2

### ISSUE THREAD

**Issue by atharen** [danielsna/team-2#3]
After reviewing the worksheet, it seemed to imply that we are **NOT to separate each document and compile them back to 1 in the end**.

We are to create one document, called _**Recipe_Book.txt**_, and each one of us has to push to that specific document.

The first individual who will push should have no issues, but any recurring pushes, will and are meant to have merge conflicts, since we cannot pull from the repository and edit _Recipe_Book.txt_.

-  I repeat **DO NOT EDIT RECIPE_BOOK.TXT FROM THE REPOSITORY**. 
- We will **DIRECTLY PUSH TO RECIPE_BOOK.TXT**.

I am aware that this would seem easy, since there is not a lot of content to merge, but this is meant to simulate a real-world working environment, where there will be a considerable amount of edits.

Besides, this is intended if we are catch any Screenshots, which will be put in the yet to be created Screenshots directory (i.e. folder). 

If you require any software that can make taking screenshots easier, I recommend [Greenshot for Windows](http://getgreenshot.org/), but this is not critical. 

I also recommend that you check for yourselves within the worksheet document at specifically point 7. 

Please reply that you acknowledge this.

In the mean time, I will delete the _Recipe_Book_Compiled_Draft_1_ directory and all the files within it.

**Comment by mattsc98** [comment]
If we are not meant to Edit Recipe_Book.txt then on what must we work on?

**Comment by atharen** [comment]
> We are to **create** one document, called Recipe_Book.txt, and each one of us has to push to that specific document.

**Comment by atharen** [comment]
Let me be more clear:
- Create your own Recipe_Book.txt
- Compile all of the work that is assigned to you.
- Push it when you are ready to Commit your work.
- IF you are the first to Push, you should have no issues, and your part will be done.
- ELSE you should get a merge conflict, which you will have to:
- Document this with a screenshot: Take note of >>>>>>>>>>>>HEAD or something similar when a conflict is detected
- Fix the document as necessary to satisfy your assignment and that of the others within the Recipe_Book.txt
- Push the change to finalize your work.
- Push the screenshot within the Screenshots directory.

If you have any more issues please post to this thread.

**Comment by atharen** [comment]
I uploaded the first Recipe_Book. 

After Reviewing it, you may notice that the Line Numbers did not align, I will fix that after everyone posts their task.

For convenience's sake, please : 
- Replace the Line Numbers within the Table of Contents with the line number where the Recipe Title is located
- Add the recipe's source below
- Follow the <> when fixing conflicting merges to better adapt your work within the source text file.

If you have any issues please feel free to contact me.

**REMEMBER** do not work on this directly, so as to allow for merge conflicts.

Also feel free to comment on the introduction/conclusion; it is still subject to change.
