### ISSUE TITLE
Creating a Merge-Conflict

### ISSUE THREAD

**Issue by atharen** [danielsna/team-2#4]
Yesterday, @danielsna and I, attempted to create the first merge-conflict; if you may have noticed that did not work out as well.

Git still managed to recognize some similarities between our documents and handled it automatically.

Now we will try again, this time make sure not to use the following characters, mainly for formatting purposes (If you use them occasionally, or are part of the recipe, then it should not matter):

- <
- \>
- ++
- \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

If this does not work, I will try to remove my version, and start off by pushing the recipes first, and I'll perform the edit later on.

I would have preferred for it to be done like this so as to allow for merge conflicts, but now I am not so sure this will be viable.

**Comment by dancam0099** [comment]
Tharen please re upload the file Recipe_Book.txt
